osx_image: xcode8.3

language: objective-c
cache: cocoapods
podfile: Podfile

before_install:
    - gem install cocoapods -v 1.2.0
    - gem install xcpretty -N

install:
    - pod outdated | awk '{ if ( $1 ~ /^-/ ) { print $0 } }' | awk '{ if ( $3 != $5 ) { pod update $2 } else { print "No updated needed for" $2 } }'

script:
    - xcodebuild -workspace glucosio.xcworkspace -scheme glucosio -destination 'name=iPhone 6s' test | xcpretty -c
